Core/add chicago project
BlickLabs/vre pull request #79
Opened 2017-03-25 03:04 UTC by AlanSanchezP

This pull request aims to resolve #75 and to resolve #78.

2017-03-25 04:13 UTC, jresendiz27 requested changes

2017-03-25 04:13 UTC, jresendiz27 commented on vre/templates/footer.html
> +      <span class="footer-logo-legend">&copy; VRE 2017</span>
Change this to use a date object maybe in python or JS

2017-03-25 04:13 UTC, jresendiz27 commented on vre/templates/develops/develop_detail_5.html
> +	      <span id="download-brochure-span" style="display:block;"></span>
I'm not a CSS expert, but inline css it's a bad practice, @Enrique199413 right?

2017-03-25 06:53 UTC, Enrique199413 commented on vre/templates/develops/develop_detail_5.html
> +	      <span id="download-brochure-span" style="display:block;"></span>
Yes is a bad practice.

http://stackoverflow.com/questions/2612483/whats-so-bad-about-in-line-css

2017-03-25 06:54 UTC, Enrique199413 commented on vre/templates/footer.html
> +      <span class="footer-logo-legend">&copy; VRE 2017</span>
For the next year changed automatically.

Brilliant!

2017-03-31 02:42 UTC, Enrique199413 reviewed
Please resolve all comments

2017-05-23 15:54 UTC, merged